---
swagger: '2.0'
info:
  version: v1
  title: ''
host: partnerapiurl
schemes:
- https
securityDefinitions:
  api_key:
    type: apiKey
    name: Authorization
    in: header
    description: "<p>All calls require HTTPS and an Authorization
    Key which will be provided by JUST EAT.<p><p>The key needs to be provided in the
    header as follows: </p><p><b>Authorization: JE-API-KEY {Your-Key-Here}</b></p>"
security:
  - api_key: []
consumes:
  - application/json
produces:
- application/json
tags:
  - name: Restaurant API
  - name: Restaurant Webhooks
  - name: Order Delivery Webhooks
  - name: Order Acceptance API
  - name: Order API
  - name: Order Delivery API
  - name: Delivery Pools API
x-tagGroups:
  - name: Delivery Pools
    tags:
      - Delivery Pools API
  - name: Order Acceptance
    tags: 
      - Order Acceptance API
  - name: Orders
    tags: 
      - Order API
  - name: Order Delivery
    tags:
      - Order Delivery Webhooks
      - Order Delivery API
  - name: Restaurants
    tags:
      - Restaurant API
      - Restaurant Webhooks