---
openapi: 3.0.0
servers:
  - url: 'https://partnerapiurl/'
externalDocs:
  description: JUST EAT Developer Contextual Documentation
  url: 'https://developers.justeat.com'
info:
  version: v1
  title: 'JUST EAT Partner API Docs'
  x-logo:
    url: "https://raw.githubusercontent.com/justeat/partnerapi-docs/master/web/logo-just-eat.png"
  description: "# Getting Started
  
  ## Security
  
  ### HTTPS

  All api calls and callbacks require HTTPS. Your service will need a valid SSL certificate and be accesible via the standard SSL port (port 443).

  ## Making an api request

  PUT https://uk-partnerapi.just-eat.io/orders/abcd1234 HTTP/1.1<br/>
  Host: uk-partnerapi.just-eat.io/<br/>
  Content-Length: 1000<br/>
  Content-Type: application/json<br/>
  Authorization: JE-API-KEY abcd123456789
  
  ## Data Formats

  ### Date and time formats

  All dates and times should use the [ISO 8601 standard for representation of dates and times](https://en.wikipedia.org/wiki/ISO_8601).


  Times recorded by Just Eat are either stored in:<br/>
  - UTC time standard with no offset; OR<br/>
  - Local time with an accompanying offset to UTC time


  All properties ending with \"WithUtcOffset\" contain local time along with an offset to UTC time.


  For instance:

  
  **DueDateWithUtcOffset**: \"2015-05-26T14:52:35.5444292+01:00\"<br/>
  Local time: 14:52<br /> 
  UTC time: 13:52<br /> 
  UTC offset: +1hr (due to daylight time saving)


  **DueDateWithUtcOffset**: \"2015-02-03T11:10:00.0000000+00:00\"<br />
  Local time: 11:10<br />
  UTC time: 11:10<br />
  UTC offset: 0 (no daylight time saving, local time is equivalent to UTC)


  Note that the offset may be for a timezone different to your own, so you should alway convert to your own local time for display purposes (e.g. on receipts and terminals).


  ### Callback timestamps

  Ideally, timestamps sent to Just Eat should be recorded as the current local time (including any changes needed to account for daylight saving) with an accompanying offset that shows the difference between the recorded local time and the current UTC time.  
  
  
  If it is not possible to record timestamps in local time, timestamps may be recorded in UTC time with a 00:00 offset.
  "
host: partnerapiurl
schemes:
- https
securityDefinitions:
  API Key:
    type: apiKey
    name: Authorization
    in: header
    description: "<p>All api calls require an Authorization
    Key which will be provided by JUST EAT.<p><p>The key needs to be provided in the
    header as follows: </p><p><b>Authorization: JE-API-KEY {Your-Key-Here}</b></p>. The key is
    case sensitive."
security:
  - API Key: []
consumes:
  - application/json
produces:
- application/json
tags:
  - name: restaurant-api
    x-displayName: Restaurant Webhooks
  - name: restaurant-api
    x-displayName: Restaurant API
  - name: order-delivery-webhooks
    x-displayName: Order Delivery Webhooks
  - name: order-acceptance-api
    x-displayName: Order Acceptance API
  - name: order-api
    x-displayName: Order API
  - name: order-webhooks
    x-displayName: Order Webhooks
  - name: order-delivery-api
    x-displayName: Order Delivery API
  - name: delivery-pools-api
    x-displayName: Delivery Pools API
x-tagGroups:
  - name: Delivery Pools
    tags:
      - delivery-pools-api
  - name: Order Acceptance
    tags: 
      - order-acceptance-api
  - name: Orders
    tags: 
      - order-api
      - order-webhooks
  - name: Order Delivery
    tags:
      - order-delivery-api
      - order-delivery-webhooks
  - name: Restaurants
    tags:
      - restaurant-api
      - restaurant-webhooks